import type { Metadata } from "next";
import Image from "next/image";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata={title:"About",description:"AEON Finvest brings clarity, perspective and long-term thinking to financial decisions."};
const values=["Clarity before complexity","Context before products","Responsibility before speed","Relationships beyond transactions"];
export default function About(){return <main><section className="page-hero"><p className="eyebrow light">About AEON</p><h1>Experience.<br/>Perspective.<br/><span style={{color:"var(--gold-light)"}}>Long-Term Thinking.</span></h1><p>We help individuals and businesses approach financial decisions with greater clarity and a wider point of view.</p></section>
<section className="section content-grid balanced-intro about-intro"><div><p className="eyebrow">Who we are</p><h2>A considered financial partner.</h2></div><div className="prose"><p>AEON Finvest Services LLP works across personal finance, property-backed lending, business capital and wealth management.</p><p>Our role is to make complex choices easier to understand. That begins with listening—carefully—to the requirement, the wider financial context and the outcomes that matter. Only then do we help frame a suitable path forward.</p><p>We believe financial guidance earns trust through candour, thoughtful analysis and consistent support.</p></div></section>
<section className="split-feature"><div className="split-image"><Image src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=85" alt="Contemporary office interior" fill sizes="(max-width:900px) 100vw, 50vw" style={{objectFit:"cover"}}/></div><div className="split-copy"><p className="eyebrow">Our approach</p><h2>Start with the whole picture.</h2><p>A financial product is only one part of a decision. We consider purpose, timing, cash flow, existing commitments and the road ahead.</p><ul>{values.map(v=><li key={v}>{v}</li>)}</ul></div></section>
<section className="section"><div className="section-head"><div><p className="eyebrow">Our philosophy</p><h2>Progress, without losing perspective.</h2></div><p>Ambition needs momentum. Good financial judgment makes sure that momentum is sustainable.</p></div><div className="why-list">{["Listen","Understand","Advise","Stay close"].map((v,i)=><Reveal key={v}><span>0{i+1}</span><h3>{v}</h3><p>{["Every mandate starts with a real conversation.","We look beyond the immediate requirement.","Options are explained plainly, with trade-offs visible.","Our support continues as circumstances evolve."][i]}</p></Reveal>)}</div></section></main>}
