import Image from "next/image";
import Link from "@/components/site-link";
import { FiArrowRight, FiCheckCircle, FiFileText, FiMessageCircle, FiSearch, FiSliders } from "react-icons/fi";
import type { Service } from "@/data/services";
const processIcons=[FiMessageCircle,FiSearch,FiSliders,FiFileText,FiCheckCircle];
export function ServiceDetail({service}: {service:Service}){return <main><section className="page-hero image"><Image src={service.image} alt={service.name} fill priority sizes="100vw"/><p className="eyebrow light">Financial solutions / {service.name}</p><h1>{service.name}</h1><p>{service.description}</p></section>
<section className="section content-grid balanced-intro service-overview"><div><p className="eyebrow">Overview</p><h2>A solution shaped around the requirement.</h2></div><div className="prose"><p>{service.short}</p><p>We help you understand the available route, the information lenders may consider and the responsibilities that come with the decision. Our work is guidance-led; all final decisions remain subject to the relevant provider’s policies and assessment.</p></div></section>
<section className="section service-detail-section"><div className="detail-columns service-detail-grid"><article><p className="eyebrow">Who it is for</p><h3>Relevant contexts</h3><ul>{service.audience.map(x=><li key={x}>{x}</li>)}</ul></article><article><p className="eyebrow">Benefits</p><h3>How we can help</h3><ul>{service.benefits.map(x=><li key={x}>{x}</li>)}</ul></article><article><p className="eyebrow">Considerations</p><h3>What to weigh</h3><ul>{service.considerations.map(x=><li key={x}>{x}</li>)}</ul></article></div></section>
<section className="dark-section process-section"><p className="eyebrow light">How it works</p><h2 style={{fontSize:"clamp(2rem,4vw,3.8rem)",fontWeight:500,letterSpacing:"-.05em"}}>A clear, measured process.</h2><ol className="steps">{service.process.map((x,i)=>{const Icon=processIcons[i]??FiCheckCircle;return <li key={x}><div className="process-card-top"><span className="process-card-number">0{i+1}</span><Icon aria-hidden="true"/></div><strong>{x}</strong></li>})}</ol></section>
<section className="section faq"><div className="section-head"><div><p className="eyebrow">Questions, answered</p><h2>Useful context before you begin.</h2></div></div>{service.faq.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section>
<section className="final-cta" style={{minHeight:560}}><div className="hero-overlay"/><div><p className="eyebrow light">Discuss {service.name}</p><h2>Ready for a clearer<br/>conversation?</h2><Link href="/contact" className="button gold">Talk to an advisor <FiArrowRight/></Link></div></section></main>}
